name: ba-tongxi-xu
extra-source-files: []
dependencies:
  - base
  - extra
  - parsec
  - containers
  - QuickCheck >= 2.14
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules:
    - Config
    - Types
    - Parsing
    - Quiz
  ghc-options:
    - -Wall
    - -Werror
executables:
  formulaFromSyntaxTree:
    main: formulaFromSyntaxTree.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Werror

tests:
  ba-tongxi-xu-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-tongxi-xu
      - hspec
