name:                ba-patrick-ritzenfeld
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2.14
- random
- containers
- hspec
- minisat-solver
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  Fill:
    main:                fill.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  GiveCnf:
    main:                giveCnf.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Pick:
    main:                pick.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Decide:
    main:                decide.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Resolve:
    main:                resolve.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Step:
    main:                step.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Write:
    main:                writer.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Robustness:
    main:                robustness.hs
    source-dirs:         app/criteria
    dependencies:
    - ba-patrick-ritzenfeld
  Difficulty:
    main:                difficulty.hs
    source-dirs:         app/criteria
    dependencies:
    - ba-patrick-ritzenfeld
  Quantity:
    main:                quantity.hs
    source-dirs:         app/criteria
    dependencies:
    - ba-patrick-ritzenfeld
  Similarity:
    main:                similarity.hs
    source-dirs:         app/criteria
    dependencies:
    - ba-patrick-ritzenfeld
tests:
  src-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ba-patrick-ritzenfeld