name: ba-tongxi-xu
extra-source-files: []
dependencies:
  - base
  - extra
  - parsec
  - containers
  - mtl
  - QuickCheck >= 2.14
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules:
    - Trees.Types
    - Trees.Helpers
    - Trees.Parsing
    - Trees.Generate
    - Trees.Print
    - Tasks.SynTree.Config
    - Tasks.SynTree.Quiz
    - Tasks.SubTree.Config
    - Tasks.SubTree.Parsing
    - Tasks.SubTree.Quiz
    - Tasks.LegalProposition.Config
    - Tasks.LegalProposition.Parsing
    - Tasks.LegalProposition.PrintIllegal
    - Tasks.LegalProposition.PrintBracket
    - Tasks.LegalProposition.Quiz
    - Tasks.SuperfluousBrackets.Config
    - Tasks.SuperfluousBrackets.Parsing
    - Tasks.SuperfluousBrackets.PrintSuperfluousBrackets
    - Tasks.SuperfluousBrackets.Quiz
    - Parsing
  ghc-options:
    - -Wall
    - -Widentities
    - -Werror
executables:
  formulaFromSyntaxTree:
    main: formulaFromSyntaxTree.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
  partNonAtomicSubTreeSet:
    main: partNonAtomicSubTreeSet.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
  illegalPseudoFormulasSelect:
    main: illegalPseudoFormulasSelect.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
  simplestFormula:
    main: simplestFormula.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
tests:
  ba-tongxi-xu-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
    dependencies:
      - ba-tongxi-xu
      - hspec
