name:                logic-tasks
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- extra
- mtl
- QuickCheck >= 2.14
- random
- containers
- hspec
- minisat-solver
- wl-pprint-text
- parsec
- text
- output-monad

library:
  source-dirs: src
  exposed-modules:
    - LogicTasks.Formula
    - LogicTasks.Table
    - LogicTasks.Resolution
    - LogicTasks.Config
    - LogicTasks.Fill
    - LogicTasks.Pick
    - LogicTasks.Decide
    - LogicTasks.Max
    - LogicTasks.Min
    - LogicTasks.Step
    - LogicTasks.Prolog
    - LogicTasks.Resolve
    - LogicTasks.Printing
    - LogicTasks.Parsing
    - LogicTasks.Util
    - Trees.Types
    - Trees.Helpers
    - Trees.Parsing
    - Trees.Generate
    - Trees.Print
    - Tasks.SynTree.Config
    - Tasks.SynTree.Quiz
    - Tasks.SubTree.Config
    - Tasks.SubTree.Parsing
    - Tasks.SubTree.Quiz
    - Tasks.LegalProposition.Config
    - Tasks.LegalProposition.Parsing
    - Tasks.LegalProposition.PrintIllegal
    - Tasks.LegalProposition.PrintBracket
    - Tasks.LegalProposition.Quiz
    - Tasks.SuperfluousBrackets.Config
    - Tasks.SuperfluousBrackets.Parsing
    - Tasks.SuperfluousBrackets.PrintSuperfluousBrackets
    - Tasks.SuperfluousBrackets.Quiz
    - Tasks.LegalCNF.Config
    - Tasks.LegalCNF.Quiz
    - Tasks.LegalCNF.GenerateIllegal
    - Tasks.LegalCNF.GenerateLegal
    - Parsing
    - ParsingHelpers
    - Config
    - Types

  ghc-options:
  - -Wall
  - -Widentities
  - -fno-warn-unused-do-bind

executables:
  formulaFromSyntaxTree:
    main: formulaFromSyntaxTree.hs
    source-dirs: app
    dependencies:
      - logic-tasks
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
  partNonAtomicSubTreeSet:
    main: partNonAtomicSubTreeSet.hs
    source-dirs: app
    dependencies:
      - logic-tasks
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
  illegalPseudoFormulasSelect:
    main: illegalPseudoFormulasSelect.hs
    source-dirs: app
    dependencies:
      - logic-tasks
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
  simplestFormula:
    main: simplestFormula.hs
    source-dirs: app
    dependencies:
      - logic-tasks
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror
  illegalCNFSelect:
    main: illegalCNFSelect.hs
    source-dirs: app
    dependencies:
      - logic-tasks
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Widentities
      - -Werror

tests:
  src-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    - -Wmissing-signatures
    - -Wunused-matches
    - -Widentities
    - -Werror
    dependencies:
    - logic-tasks
