name:                logic-tasks
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2.14
- random
- containers
- hspec
- minisat-solver

library:
  source-dirs: src
  exposed-modules:
    - Formula
    - Table
    - Resolution


  ghc-options:
  - -Wall

tests:
  src-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logic-tasks
