name: ba-tongxi-xu
extra-source-files: []
dependencies:
  - base
  - extra
  - parsec
  - containers
  - mtl
  - QuickCheck >= 2.14
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules:
    - Tasks.SynTree.Config
    - Tasks.SubTree.Config
    - Tasks.LegalProposition.Config
    - Tasks.SuperfluousBrackets.Config
    - Types
    - Parsing
    - Generate
    - Print
    - Tasks.SynTree.Quiz
    - Tasks.SubTree.Quiz
    - Tasks.LegalProposition.Quiz
    - Tasks.SuperfluousBrackets.Quiz
    - Tasks.SuperfluousBrackets.PrintSuperfluousBrackets
    - Tasks.LegalProposition.PrintIllegal
    - Tasks.LegalProposition.PrintBracket
  ghc-options:
    - -Wall
    - -Werror
executables:
  formulaFromSyntaxTree:
    main: formulaFromSyntaxTree.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Werror
  partNonAtomicSubTreeSet:
    main: partNonAtomicSubTreeSet.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Werror
  illegalPseudoFormulasSelect:
    main: illegalPseudoFormulasSelect.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Werror
  simplestFormula:
    main: simplestFormula.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu
      - pretty-simple
    ghc-options:
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Werror
tests:
  ba-tongxi-xu-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wunused-imports
      - -Wmissing-signatures
      - -Wunused-matches
      - -Werror
    dependencies:
      - ba-tongxi-xu
      - hspec
