name: ba-tongxi-xu
extra-source-files: []
dependencies:
  - base
  - extra
  - parsec
  - containers
  - QuickCheck >= 2.14
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules: 
    - Types
    - Parsing
  ghc-options:
    - -Wall
    - -Werror
executables:
  default:
    main: default.hs
    source-dirs: app
    dependencies:
      - ba-tongxi-xu

tests:
  ba-tongxi-xu-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-tongxi-xu
      - hspec
