name:                ba-patrick-ritzenfeld
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2.14
- random
- containers
- hspec 

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  Fill: 
    main:                fill.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Cnf: 
    main:                giveCnf.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Pick: 
    main:                pick.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Decide: 
    main:                decide.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Resolve: 
    main:                resolve.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
  Step: 
    main:                step.hs
    source-dirs:         app
    dependencies:
    - ba-patrick-ritzenfeld
    
    
tests:
  src-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ba-patrick-ritzenfeld