name:                logic-tasks
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2.14
- random
- containers
- hspec
- minisat-solver
- wl-pprint-text
- parsec
- text

library:
  source-dirs: src
  exposed-modules:
    - LogicTasks.Formula
    - LogicTasks.Table
    - LogicTasks.Resolution
    - LogicTasks.Config
    - LogicTasks.Fill
    - LogicTasks.Pick
    - LogicTasks.Decide
    - LogicTasks.Max
    - LogicTasks.Min
    - LogicTasks.Step
    - LogicTasks.Prolog
    - LogicTasks.Resolve
    - LogicTasks.Printing
    - LogicTasks.Parsing
    - LogicTasks.Util

  ghc-options:
  - -Wall

tests:
  src-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logic-tasks
