---
resolver: lts-20.26

packages:
  - .
allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-monad.git
    commit: dee586e12b62b0b854070c1bbd59749ad7ff3b0c
    subdirs:
      - output-monad
