---
resolver: lts-20.18

packages:
  - .
allow-newer: true
extra-deps:
  - minisat-solver-0.1
  - latex-svg-image-0.2
  - git: https://github.com/fmidue/output-monad.git
    commit: c953b14c2b73dfb9cb5749c999cdc63702b8cb8c
    subdirs:
      - output-monad
