resolver: lts-16.31

ghc-options:
    # All packages
    "$locals":
      -Wall
      -fno-warn-unused-do-bind

packages:
  - .

extra-deps:
  - QuickCheck-2.14
  - minisat-solver-0.1
  - git: https://github.com/fmidue/output-monad.git
    commit: d51169e89ecfc736e12f36732b08d53460c2bb4f
    subdirs:
      - output-monad
