---
name: logic-tasks-examples
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - logic-tasks
  - output-monad
  - hspec

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Widentities
    - -fno-warn-unused-do-bind
    - -Werror
    - -Wwarn=incomplete-uni-patterns
    - -Wwarn=x-partial
    - -Wwarn=unrecognised-warning-flags # should be removed when on lts-22 or later
    - -fdefer-typed-holes

tests:
  verify-configs:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wunused-imports
      - -Wmissing-signatures
      - -Werror
    dependencies:
      - logic-tasks-examples
      - hspec
